name: olympus-sdk
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=20.3.0
  - base58=2.1.0
  - bitarray=1.2.2
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - cytoolz=0.11.0
  - eth-abi=2.1.1
  - eth-account=0.5.4
  - eth-hash=0.3.1
  - eth-keyfile=0.5.1
  - eth-keys=0.3.3
  - eth-rlp=0.2.1
  - eth-typing=2.2.2
  - eth-utils=1.10.0
  - gmp=6.2.1
  - h11=0.12.0
  - h2=4.0.0
  - hexbytes=0.2.1
  - hpack=4.0.0
  - httpcore=0.12.3
  - httpx=0.17.1
  - hyperframe=6.0.0
  - idna=2.10
  - importlib-metadata=3.10.1
  - iniconfig=1.1.1
  - ipfshttpclient=0.7.0
  - jsonschema=3.2.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libprotobuf=3.15.8
  - libstdcxx-ng=9.3.0
  - lru-dict=1.1.6
  - more-itertools=8.7.0
  - multiaddr=0.0.9
  - ncurses=6.2
  - netaddr=0.7.19
  - openssl=1.1.1k
  - packaging=20.9
  - parsimonious=0.8.1
  - pip=21.0.1
  - pluggy=0.13.1
  - protobuf=3.15.8
  - py=1.10.0
  - pycparser=2.20
  - pycryptodome=3.10.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.2.3
  - python=3.9.2
  - python_abi=3.9
  - readline=8.1
  - requests=2.25.1
  - rfc3986=1.4.0
  - rlp=1.2.0
  - setuptools=49.6.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.35.4
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tzdata=2021a
  - urllib3=1.26.4
  - varint=1.0.2
  - web3=5.18.0
  - websockets=8.1
  - wheel=0.36.2
  - xz=5.2.5
  - zipp=3.4.1
  - zlib=1.2.11
